<?php

namespace Database\Seeders;

use App\Models\RouteCities;
use App\Models\Routes;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        $users = [
            [
                'name' => 'John Doe',
                'email' => 'admin@admin.com',
                'password' => bcrypt('1234567890'),
                'is_admin' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'John Doe',
                'email' => 'user@user.com',
                'password' => bcrypt('1234567890'),
                'is_admin' => true,
                'created_at' => now(),
                'updated_at' => now()
            ],
        ];

        foreach($users as $user) {
            DB::table('users')->insert($user);
        }

        $types = [
            ['id' => 1, 'name' => 'Sedan', 'rental_within' => '2500', 'rental_without' => '4000'],
            ['id' => 2, 'name' => 'Hatchback', 'rental_within' => '0', 'rental_without' => '0'],
            ['id' => 3, 'name' => 'Crossover', 'rental_within' => '0', 'rental_without' => '0'],
            ['id' => 4, 'name' => 'SUV', 'rental_within' => '3500', 'rental_without' => '5500'],
            ['id' => 5, 'name' => 'Luxury Van', 'rental_within' => '8500', 'rental_without' => '8500'],
            ['id' => 6, 'name' => 'Pickup', 'rental_within' => '3600', 'rental_without' => '5500'],
            ['id' => 7, 'name' => 'Van', 'rental_within' => '5500', 'rental_without' => '7500'],
            ['id' => 8, 'name' => 'Minivan', 'rental_within' => '0', 'rental_without' => '0'],
            ['id' => 9, 'name' => 'Sports Car', 'rental_within' => '0', 'rental_without' => '0'],
            ['id' => 10, 'name' => 'Electric Vehicle (EV)', 'rental_within' => '0', 'rental_without' => '0'],
            ['id' => 11, 'name' => 'Hybrid', 'rental_within' => '0', 'rental_without' => '0'],
        ];

        $brands = [
            'Toyota',
            'Mitsubishi',
            'Honda',
            'Ford',
            'Nissan',
            'Suzuki',
            'Isuzu',
            'Hyundai',
            'Chevrolet',
            'Kia',
        ];

        $models = [
            ['id' => 1, 'name' => 'Toyota', 'models' => [
                ['brand_id' => 1, 'name' => 'Vios', 'type_id' => 1],
                ['brand_id' => 1, 'name' => 'Wigo', 'type_id' => 2],
                ['brand_id' => 1, 'name' => 'Corolla Cross', 'type_id' => 3],
                ['brand_id' => 1, 'name' => 'Fortuner', 'type_id' => 4],
                ['brand_id' => 1, 'name' => 'Land Cruiser', 'type_id' => 5],
                ['brand_id' => 1, 'name' => 'Hilux', 'type_id' => 6],
                ['brand_id' => 1, 'name' => 'HiAce', 'type_id' => 7],
                ['brand_id' => 1, 'name' => 'Innova', 'type_id' => 8],
                ['brand_id' => 1, 'name' => 'Rush', 'type_id' => 3],
            ]],
            ['id' => 2, 'name' => 'Mitsubishi', 'models' => [
                ['brand_id' => 2, 'name' => 'Mirage G4', 'type_id' => 1],
                ['brand_id' => 2, 'name' => 'Xpander', 'type_id' => 3],
                ['brand_id' => 2, 'name' => 'Montero Sport', 'type_id' => 4],
                ['brand_id' => 2, 'name' => 'Strada', 'type_id' => 6],
                ['brand_id' => 2, 'name' => 'L300', 'type_id' => 7],
            ]],
            ['id' => 3, 'name' => 'Honda', 'models' => [
                ['brand_id' => 3, 'name' => 'City', 'type_id' => 1],
                ['brand_id' => 3, 'name' => 'Brio', 'type_id' => 2],
                ['brand_id' => 3, 'name' => 'HR-V', 'type_id' => 3],
                ['brand_id' => 3, 'name' => 'CR-V', 'type_id' => 4],
                ['brand_id' => 3, 'name' => 'BR-V', 'type_id' => 3],
            ]],
            ['id' => 4, 'name' => 'Ford', 'models' => [
                ['brand_id' => 4, 'name' => 'Everest', 'type_id' => 4],
                ['brand_id' => 4, 'name' => 'Ranger', 'type_id' => 6],
                ['brand_id' => 4, 'name' => 'Territory', 'type_id' => 3],
                ['brand_id' => 4, 'name' => 'Mustang', 'type_id' => 9],
            ]],
            ['id' => 5, 'name' => 'Nissan', 'models' => [
                ['brand_id' => 5, 'name' => 'Almera', 'type_id' => 1],
                ['brand_id' => 5, 'name' => 'Navara', 'type_id' => 6],
                ['brand_id' => 5, 'name' => 'Terra', 'type_id' => 4],
                ['brand_id' => 5, 'name' => 'Urvan', 'type_id' => 7],
            ]],
            ['id' => 6, 'name' => 'Suzuki', 'models' => [
                ['brand_id' => 6, 'name' => 'Ertiga', 'type_id' => 8],
                ['brand_id' => 6, 'name' => 'Dzire', 'type_id' => 1],
                ['brand_id' => 6, 'name' => 'Celerio', 'type_id' => 2],
                ['brand_id' => 6, 'name' => 'Jimny', 'type_id' => 4],
            ]],
            ['id' => 7, 'name' => 'Isuzu', 'models' => [
                ['brand_id' => 7, 'name' => 'D-Max', 'type_id' => 6],
                ['brand_id' => 7, 'name' => 'MU-X', 'type_id' => 4],
            ]],
            ['id' => 8, 'name' => 'Hyundai', 'models' => [
                ['brand_id' => 8, 'name' => 'Accent', 'type_id' => 1],
                ['brand_id' => 8, 'name' => 'Tucson', 'type_id' => 3],
                ['brand_id' => 8, 'name' => 'Staria', 'type_id' => 5],
            ]],
            ['id' => 9, 'name' => 'Chevrolet', 'models' => [
                ['brand_id' => 9, 'name' => 'Trailblazer', 'type_id' => 4],
                ['brand_id' => 9, 'name' => 'Tracker', 'type_id' => 3],
            ]],
            ['id' => 10, 'name' => 'Kia', 'models' => [
                ['brand_id' => 10, 'name' => 'Soluto', 'type_id' => 1],
                ['brand_id' => 10, 'name' => 'Seltos', 'type_id' => 3],
                ['brand_id' => 10, 'name' => 'Carnival', 'type_id' => 8],
            ]],
        ];

        foreach ($types as $car_type) {
            DB::table('car_types')->insert([
                'name' => $car_type['name'],
                'rental_within' => $car_type['rental_within'],
                'rental_without' => $car_type['rental_without'],
            ]);
        }

        foreach ($brands as $brand) {
            DB::table('car_brands')->insert(['name' => $brand]);
        }

        foreach ($models as $brand) {
            foreach ($brand['models'] as $model) {
                DB::table('car_models')->insert([
                    'brand_id' => $model['brand_id'],
                    'name' => $model['name'],
                    'type_id' => $model['type_id']
                ]);
            }
        }

        foreach($models as $brand) {
            $brand_id = $brand['id'];
            $models = $brand['models'];
            foreach($models as $model) {
                $model['brand_id'] = $brand_id;
                DB::table('car_models')->insert($model);
            }
        }


        $colors = [
            'White',
            'Black',
            'Silver',
            'Gray',
            'Red',
            'Blue',
            'Yellow',
            'Orange',
            'Green',
            'Purple',
            'Matte Black',
            'Matte Gray',
            'Matte Red',
            'Matte Blue',
            'Matte Yellow',
            'Matte Orange',
        ];

        foreach($colors as $color) {
            DB::table('car_colors')->insert(['name' => $color]);
        }

        $status = [
            'Pending',
            'Approved',
            'Declined',
            'Cancelled',
            'Completed'
        ];

        foreach($status as $stat) {
            DB::table('car_statuses')->insert(['name' => $stat]);
        }

        $payment_modes = [
            'Cash',
            'GCash',
            'PayMaya',
            'Credit Card',
        ];

        foreach($payment_modes as $mode) {
            DB::table('payment_modes')->insert(['name' => $mode]);
        }

        $province = [
            ['id' => 1, 'name' => 'Abra', 'cities' => [
                ['province_id' => 1, 'name' => 'Bangued'],
                ['province_id' => 1, 'name' => 'Boliney'],
                ['province_id' => 1, 'name' => 'Bucay'],
                ['province_id' => 1, 'name' => 'Bucloc'],
                ['province_id' => 1, 'name' => 'Daguioman'],
                ['province_id' => 1, 'name' => 'Danglas'],
                ['province_id' => 1, 'name' => 'Dolores'],
                ['province_id' => 1, 'name' => 'La Paz'],
                ['province_id' => 1, 'name' => 'Lacub'],
                ['province_id' => 1, 'name' => 'Lagangilang'],
                ['province_id' => 1, 'name' => 'Lagayan'],
                ['province_id' => 1, 'name' => 'Langiden'],
                ['province_id' => 1, 'name' => 'Licuan-Baay'],
                ['province_id' => 1, 'name' => 'Luba'],
                ['province_id' => 1, 'name' => 'Malibcong'],
                ['province_id' => 1, 'name' => 'Manabo'],
                ['province_id' => 1, 'name' => 'Peñarrubia'],
                ['province_id' => 1, 'name' => 'Pidigan'],
                ['province_id' => 1, 'name' => 'Pilar'],
                ['province_id' => 1, 'name' => 'Sallapadan'],
                ['province_id' => 1, 'name' => 'San Isidro'],
                ['province_id' => 1, 'name' => 'San Juan'],
                ['province_id' => 1, 'name' => 'San Quintin'],
                ['province_id' => 1, 'name' => 'Tayum'],
                ['province_id' => 1, 'name' => 'Tineg'],
                ['province_id' => 1, 'name' => 'Tubo'],
                ['province_id' => 1, 'name' => 'Villaviciosa']
            ]],
            ['id' => 2, 'name' => 'Albay', 'cities' => [
                ['province_id' => 2, 'name' => 'Legazpi City'],
                ['province_id' => 2, 'name' => 'Ligao City'],
                ['province_id' => 2, 'name' => 'Tabaco City'],
                ['province_id' => 2, 'name' => 'Bacacay'],
                ['province_id' => 2, 'name' => 'Camalig'],
                ['province_id' => 2, 'name' => 'Daraga'],
                ['province_id' => 2, 'name' => 'Guinobatan'],
                ['province_id' => 2, 'name' => 'Jovellar'],
                ['province_id' => 2, 'name' => 'Libon'],
                ['province_id' => 2, 'name' => 'Malilipot'],
                ['province_id' => 2, 'name' => 'Malinao'],
                ['province_id' => 2, 'name' => 'Manito'],
                ['province_id' => 2, 'name' => 'Oas'],
                ['province_id' => 2, 'name' => 'Pio Duran'],
                ['province_id' => 2, 'name' => 'Polangui'],
                ['province_id' => 2, 'name' => 'Rapu-Rapu'],
                ['province_id' => 2, 'name' => 'Santo Domingo'],
                ['province_id' => 2, 'name' => 'Tiwi']
            ]],
            ['id' => 3, 'name' => 'Apayao', 'cities' => [
                ['province_id' => 3, 'name' => 'Calanasan'],
                ['province_id' => 3, 'name' => 'Conner'],
                ['province_id' => 3, 'name' => 'Flora'],
                ['province_id' => 3, 'name' => 'Kabugao'],
                ['province_id' => 3, 'name' => 'Luna'],
                ['province_id' => 3, 'name' => 'Pudtol'],
                ['province_id' => 3, 'name' => 'Santa Marcela']
            ]],
            ['id' => 4, 'name' => 'Aurora', 'cities' => [
                ['province_id' => 4, 'name' => 'Baler'],
                ['province_id' => 4, 'name' => 'Casiguran'],
                ['province_id' => 4, 'name' => 'Dilasag'],
                ['province_id' => 4, 'name' => 'Dinalungan'],
                ['province_id' => 4, 'name' => 'Dingalan'],
                ['province_id' => 4, 'name' => 'Dipaculao'],
                ['province_id' => 4, 'name' => 'Maria Aurora'],
                ['province_id' => 4, 'name' => 'San Luis']
            ]],
            ['id' => 5, 'name' => 'Bataan', 'cities' => [
                ['province_id' => 5, 'name' => 'Balanga City'],
                ['province_id' => 5, 'name' => 'Abucay'],
                ['province_id' => 5, 'name' => 'Bagac'],
                ['province_id' => 5, 'name' => 'Dinalupihan'],
                ['province_id' => 5, 'name' => 'Hermosa'],
                ['province_id' => 5, 'name' => 'Limay'],
                ['province_id' => 5, 'name' => 'Mariveles'],
                ['province_id' => 5, 'name' => 'Morong'],
                ['province_id' => 5, 'name' => 'Orani'],
                ['province_id' => 5, 'name' => 'Orion'],
                ['province_id' => 5, 'name' => 'Pilar'],
                ['province_id' => 5, 'name' => 'Samal']
            ]],
            ['id' => 6, 'name' => 'Batanes', 'cities' => [
                ['province_id' => 6, 'name' => 'Basco'],
                ['province_id' => 6, 'name' => 'Itbayat'],
                ['province_id' => 6, 'name' => 'Ivana'],
                ['province_id' => 6, 'name' => 'Mahatao'],
                ['province_id' => 6, 'name' => 'Sabtang'],
                ['province_id' => 6, 'name' => 'Uyugan']
            ]],
            ['id' => 8, 'name' => 'Batanes', 'cities' => [
                ['province_id' => 8, 'name' => 'Basco'],
                ['province_id' => 8, 'name' => 'Itbayat'],
                ['province_id' => 8, 'name' => 'Ivana'],
                ['province_id' => 8, 'name' => 'Mahatao'],
                ['province_id' => 8, 'name' => 'Sabtang'],
                ['province_id' => 8, 'name' => 'Uyugan']
            ]],
            ['id' => 9, 'name' => 'Batangas', 'cities' => [
                ['province_id' => 9, 'name' => 'Batangas City'],
                ['province_id' => 9, 'name' => 'Lipa City'],
                ['province_id' => 9, 'name' => 'Tanauan City'],
                ['province_id' => 9, 'name' => 'Agoncillo'],
                ['province_id' => 9, 'name' => 'Alitagtag'],
                ['province_id' => 9, 'name' => 'Balayan'],
                ['province_id' => 9, 'name' => 'Balete'],
                ['province_id' => 9, 'name' => 'Bauan'],
                ['province_id' => 9, 'name' => 'Calaca'],
                ['province_id' => 9, 'name' => 'Calatagan'],
                ['province_id' => 9, 'name' => 'Cuenca'],
                ['province_id' => 9, 'name' => 'Ibaan'],
                ['province_id' => 9, 'name' => 'Laurel'],
                ['province_id' => 9, 'name' => 'Lemery'],
                ['province_id' => 9, 'name' => 'Lian'],
                ['province_id' => 9, 'name' => 'Mabini'],
                ['province_id' => 9, 'name' => 'Malvar'],
                ['province_id' => 9, 'name' => 'Mataasnakahoy'],
                ['province_id' => 9, 'name' => 'Nasugbu'],
                ['province_id' => 9, 'name' => 'Padre Garcia'],
                ['province_id' => 9, 'name' => 'Rosario'],
                ['province_id' => 9, 'name' => 'San Jose'],
                ['province_id' => 9, 'name' => 'San Juan'],
                ['province_id' => 9, 'name' => 'San Luis'],
                ['province_id' => 9, 'name' => 'San Nicolas'],
                ['province_id' => 9, 'name' => 'San Pascual'],
                ['province_id' => 9, 'name' => 'Santa Teresita'],
                ['province_id' => 9, 'name' => 'Taal'],
                ['province_id' => 9, 'name' => 'Talisay'],
                ['province_id' => 9, 'name' => 'Taysan'],
                ['province_id' => 9, 'name' => 'Tingloy'],
                ['province_id' => 9, 'name' => 'Tuy']
            ]],
            ['id' => 10, 'name' => 'Benguet', 'cities' => [
                ['province_id' => 10, 'name' => 'Baguio City'],
                ['province_id' => 10, 'name' => 'Atok'],
                ['province_id' => 10, 'name' => 'Bakun'],
                ['province_id' => 10, 'name' => 'Bokod'],
                ['province_id' => 10, 'name' => 'Buguias'],
                ['province_id' => 10, 'name' => 'Itogon'],
                ['province_id' => 10, 'name' => 'Kabayan'],
                ['province_id' => 10, 'name' => 'Kapangan'],
                ['province_id' => 10, 'name' => 'Kibungan'],
                ['province_id' => 10, 'name' => 'La Trinidad'],
                ['province_id' => 10, 'name' => 'Mankayan'],
                ['province_id' => 10, 'name' => 'Sablan'],
                ['province_id' => 10, 'name' => 'Tuba'],
                ['province_id' => 10, 'name' => 'Tublay']
            ]],
            ['id' => 11, 'name' => 'Bulacan', 'cities' => [
                ['province_id' => 11, 'name' => 'Malolos City'],
                ['province_id' => 11, 'name' => 'Meycauayan City'],
                ['province_id' => 11, 'name' => 'San Jose del Monte City'],
                ['province_id' => 11, 'name' => 'Angat'],
                ['province_id' => 11, 'name' => 'Balagtas'],
                ['province_id' => 11, 'name' => 'Baliuag'],
                ['province_id' => 11, 'name' => 'Bocaue'],
                ['province_id' => 11, 'name' => 'Bulakan'],
                ['province_id' => 11, 'name' => 'Bustos'],
                ['province_id' => 11, 'name' => 'Calumpit'],
                ['province_id' => 11, 'name' => 'Doña Remedios Trinidad'],
                ['province_id' => 11, 'name' => 'Guiguinto'],
                ['province_id' => 11, 'name' => 'Hagonoy'],
                ['province_id' => 11, 'name' => 'Marilao'],
                ['province_id' => 11, 'name' => 'Norzagaray'],
                ['province_id' => 11, 'name' => 'Obando'],
                ['province_id' => 11, 'name' => 'Pandi'],
                ['province_id' => 11, 'name' => 'Paombong'],
                ['province_id' => 11, 'name' => 'Plaridel'],
                ['province_id' => 11, 'name' => 'Pulilan'],
                ['province_id' => 11, 'name' => 'San Ildefonso'],
                ['province_id' => 11, 'name' => 'San Miguel'],
                ['province_id' => 11, 'name' => 'San Rafael'],
                ['province_id' => 11, 'name' => 'Santa Maria']
            ]],
            ['id' => 12, 'name' => 'Cagayan', 'cities' => [
                ['province_id' => 12, 'name' => 'Tuguegarao City'],
                ['province_id' => 12, 'name' => 'Abulug'],
                ['province_id' => 12, 'name' => 'Alcala'],
                ['province_id' => 12, 'name' => 'Allacapan'],
                ['province_id' => 12, 'name' => 'Amulung'],
                ['province_id' => 12, 'name' => 'Aparri'],
                ['province_id' => 12, 'name' => 'Baggao'],
                ['province_id' => 12, 'name' => 'Ballesteros'],
                ['province_id' => 12, 'name' => 'Buguey'],
                ['province_id' => 12, 'name' => 'Calayan'],
                ['province_id' => 12, 'name' => 'Camalaniugan'],
                ['province_id' => 12, 'name' => 'Claveria'],
                ['province_id' => 12, 'name' => 'Enrile'],
                ['province_id' => 12, 'name' => 'Gattaran'],
                ['province_id' => 12, 'name' => 'Gonzaga'],
                ['province_id' => 12, 'name' => 'Iguig'],
                ['province_id' => 12, 'name' => 'Lal-lo'],
                ['province_id' => 12, 'name' => 'Lasam'],
                ['province_id' => 12, 'name' => 'Pamplona'],
                ['province_id' => 12, 'name' => 'Peñablanca'],
                ['province_id' => 12, 'name' => 'Piat'],
                ['province_id' => 12, 'name' => 'Rizal'],
                ['province_id' => 12, 'name' => 'Sanchez-Mira'],
                ['province_id' => 12, 'name' => 'Santa Ana'],
                ['province_id' => 12, 'name' => 'Santa Praxedes'],
                ['province_id' => 12, 'name' => 'Santa Teresita'],
                ['province_id' => 12, 'name' => 'Santo Niño'],
                ['province_id' => 12, 'name' => 'Solana'],
                ['province_id' => 12, 'name' => 'Tuao']
            ]],
            ['id' => 13, 'name' => 'Camarines Norte', 'cities' => [
                ['province_id' => 13, 'name' => 'Daet'],
                ['province_id' => 13, 'name' => 'Basud'],
                ['province_id' => 13, 'name' => 'Capalonga'],
                ['province_id' => 13, 'name' => 'Jose Panganiban'],
                ['province_id' => 13, 'name' => 'Labo'],
                ['province_id' => 13, 'name' => 'Mercedes'],
                ['province_id' => 13, 'name' => 'Paracale'],
                ['province_id' => 13, 'name' => 'San Lorenzo Ruiz'],
                ['province_id' => 13, 'name' => 'San Vicente'],
                ['province_id' => 13, 'name' => 'Santa Elena'],
                ['province_id' => 13, 'name' => 'Talisay'],
                ['province_id' => 13, 'name' => 'Vinzons']
            ]],
            ['id' => 14, 'name' => 'Camarines Sur', 'cities' => [
                ['province_id' => 14, 'name' => 'Naga City'],
                ['province_id' => 14, 'name' => 'Iriga City'],
                ['province_id' => 14, 'name' => 'Baao'],
                ['province_id' => 14, 'name' => 'Balatan'],
                ['province_id' => 14, 'name' => 'Bato'],
                ['province_id' => 14, 'name' => 'Bombon'],
                ['province_id' => 14, 'name' => 'Buhi'],
                ['province_id' => 14, 'name' => 'Bula'],
                ['province_id' => 14, 'name' => 'Cabusao'],
                ['province_id' => 14, 'name' => 'Calabanga'],
                ['province_id' => 14, 'name' => 'Camaligan'],
                ['province_id' => 14, 'name' => 'Canaman'],
                ['province_id' => 14, 'name' => 'Caramoan'],
                ['province_id' => 14, 'name' => 'Del Gallego'],
                ['province_id' => 14, 'name' => 'Gainza'],
                ['province_id' => 14, 'name' => 'Garchitorena'],
                ['province_id' => 14, 'name' => 'Goa'],
                ['province_id' => 14, 'name' => 'Lagonoy'],
                ['province_id' => 14, 'name' => 'Libmanan'],
                ['province_id' => 14, 'name' => 'Lupi'],
                ['province_id' => 14, 'name' => 'Magarao'],
                ['province_id' => 14, 'name' => 'Milaor'],
                ['province_id' => 14, 'name' => 'Minalabac'],
                ['province_id' => 14, 'name' => 'Nabua'],
                ['province_id' => 14, 'name' => 'Ocampo'],
                ['province_id' => 14, 'name' => 'Pamplona'],
                ['province_id' => 14, 'name' => 'Pasacao'],
                ['province_id' => 14, 'name' => 'Pili'],
                ['province_id' => 14, 'name' => 'Presentacion'],
                ['province_id' => 14, 'name' => 'Ragay'],
                ['province_id' => 14, 'name' => 'Sagñay'],
                ['province_id' => 14, 'name' => 'San Fernando'],
                ['province_id' => 14, 'name' => 'San Jose'],
                ['province_id' => 14, 'name' => 'Sipocot'],
                ['province_id' => 14, 'name' => 'Siruma'],
                ['province_id' => 14, 'name' => 'Tigaon'],
                ['province_id' => 14, 'name' => 'Tinambac']
            ]],
            ['id' => 15, 'name' => 'Catanduanes', 'cities' => [
                ['province_id' => 15, 'name' => 'Virac'],
                ['province_id' => 15, 'name' => 'Bagamanoc'],
                ['province_id' => 15, 'name' => 'Baras'],
                ['province_id' => 15, 'name' => 'Bato'],
                ['province_id' => 15, 'name' => 'Caramoran'],
                ['province_id' => 15, 'name' => 'Gigmoto'],
                ['province_id' => 15, 'name' => 'Pandan'],
                ['province_id' => 15, 'name' => 'Panganiban'],
                ['province_id' => 15, 'name' => 'San Andres'],
                ['province_id' => 15, 'name' => 'San Miguel'],
                ['province_id' => 15, 'name' => 'Viga']
            ]],
            ['id' => 16, 'name' => 'Isabela', 'cities' => [
                ['province_id' => 16, 'name' => 'Cauayan City'],
                ['province_id' => 16, 'name' => 'Santiago City'],
                ['province_id' => 16, 'name' => 'Alicia'],
                ['province_id' => 16, 'name' => 'Angadanan'],
                ['province_id' => 16, 'name' => 'Aurora'],
                ['province_id' => 16, 'name' => 'Benito Soliven'],
                ['province_id' => 16, 'name' => 'Burgos'],
                ['province_id' => 16, 'name' => 'Cabagan'],
                ['province_id' => 16, 'name' => 'Cabatuan'],
                ['province_id' => 16, 'name' => 'Cordon'],
                ['province_id' => 16, 'name' => 'Delfin Albano'],
                ['province_id' => 16, 'name' => 'Dinapigue'],
                ['province_id' => 16, 'name' => 'Divilacan'],
                ['province_id' => 16, 'name' => 'Echague'],
                ['province_id' => 16, 'name' => 'Gamu'],
                ['province_id' => 16, 'name' => 'Ilagan City'],
                ['province_id' => 16, 'name' => 'Jones'],
                ['province_id' => 16, 'name' => 'Luna'],
                ['province_id' => 16, 'name' => 'Maconacon'],
                ['province_id' => 16, 'name' => 'Mallig'],
                ['province_id' => 16, 'name' => 'Naguilian'],
                ['province_id' => 16, 'name' => 'Palanan'],
                ['province_id' => 16, 'name' => 'Quezon'],
                ['province_id' => 16, 'name' => 'Quirino'],
                ['province_id' => 16, 'name' => 'Ramon'],
                ['province_id' => 16, 'name' => 'Reina Mercedes'],
                ['province_id' => 16, 'name' => 'Roxas'],
                ['province_id' => 16, 'name' => 'San Agustin'],
                ['province_id' => 16, 'name' => 'San Guillermo'],
                ['province_id' => 16, 'name' => 'San Isidro'],
                ['province_id' => 16, 'name' => 'San Manuel'],
                ['province_id' => 16, 'name' => 'San Mariano'],
                ['province_id' => 16, 'name' => 'San Mateo'],
                ['province_id' => 16, 'name' => 'Santa Maria'],
                ['province_id' => 16, 'name' => 'Santo Tomas'],
                ['province_id' => 16, 'name' => 'Tumauini']
            ]],
            ['id' => 17, 'name' => 'Bataan', 'cities' => [
                ['province_id' => 17, 'name' => 'Balanga City'],
                ['province_id' => 17, 'name' => 'Abucay'],
                ['province_id' => 17, 'name' => 'Bagac'],
                ['province_id' => 17, 'name' => 'Dinalupihan'],
                ['province_id' => 17, 'name' => 'Hermosa'],
                ['province_id' => 17, 'name' => 'Limay'],
                ['province_id' => 17, 'name' => 'Mariveles'],
                ['province_id' => 17, 'name' => 'Morong'],
                ['province_id' => 17, 'name' => 'Orani'],
                ['province_id' => 17, 'name' => 'Orion'],
                ['province_id' => 17, 'name' => 'Pilar'],
                ['province_id' => 17, 'name' => 'Samal']
            ]],
            ['id' => 18, 'name' => 'Batangas', 'cities' => [
                ['province_id' => 18, 'name' => 'Batangas City'],
                ['province_id' => 18, 'name' => 'Lipa City'],
                ['province_id' => 18, 'name' => 'Tanauan City'],
                ['province_id' => 18, 'name' => 'Agoncillo'],
                ['province_id' => 18, 'name' => 'Alitagtag'],
                ['province_id' => 18, 'name' => 'Balayan'],
                ['province_id' => 18, 'name' => 'Balete'],
                ['province_id' => 18, 'name' => 'Bauan'],
                ['province_id' => 18, 'name' => 'Calaca'],
                ['province_id' => 18, 'name' => 'Calatagan'],
                ['province_id' => 18, 'name' => 'Cuenca'],
                ['province_id' => 18, 'name' => 'Ibaan'],
                ['province_id' => 18, 'name' => 'Laurel'],
                ['province_id' => 18, 'name' => 'Lemery'],
                ['province_id' => 18, 'name' => 'Lian'],
                ['province_id' => 18, 'name' => 'Mabini'],
                ['province_id' => 18, 'name' => 'Malvar'],
                ['province_id' => 18, 'name' => 'Mataasnakahoy'],
                ['province_id' => 18, 'name' => 'Nasugbu'],
                ['province_id' => 18, 'name' => 'Padre Garcia'],
                ['province_id' => 18, 'name' => 'Rosario'],
                ['province_id' => 18, 'name' => 'San Jose'],
                ['province_id' => 18, 'name' => 'San Juan'],
                ['province_id' => 18, 'name' => 'San Luis'],
                ['province_id' => 18, 'name' => 'San Nicolas'],
                ['province_id' => 18, 'name' => 'San Pascual'],
                ['province_id' => 18, 'name' => 'Santa Teresita'],
                ['province_id' => 18, 'name' => 'Taal'],
                ['province_id' => 18, 'name' => 'Talisay'],
                ['province_id' => 18, 'name' => 'Taysan'],
                ['province_id' => 18, 'name' => 'Tingloy'],
                ['province_id' => 18, 'name' => 'Tuy']
            ]],
            ['id' => 19, 'name' => 'Nueva Vizcaya', 'cities' => [
                ['province_id' => 19, 'name' => 'Bayombong'],
                ['province_id' => 19, 'name' => 'Alfonso Castañeda'],
                ['province_id' => 19, 'name' => 'Ambaguio'],
                ['province_id' => 19, 'name' => 'Aritao'],
                ['province_id' => 19, 'name' => 'Bagabag'],
                ['province_id' => 19, 'name' => 'Diadi'],
                ['province_id' => 19, 'name' => 'Dupax del Norte'],
                ['province_id' => 19, 'name' => 'Dupax del Sur'],
                ['province_id' => 19, 'name' => 'Kasibu'],
                ['province_id' => 19, 'name' => 'Kayapa'],
                ['province_id' => 19, 'name' => 'Quezon'],
                ['province_id' => 19, 'name' => 'Santa Fe'],
                ['province_id' => 19, 'name' => 'Solano'],
                ['province_id' => 19, 'name' => 'Villaverde']
            ]],
            ['id' => 20, 'name' => 'Quirino', 'cities' => [
                ['province_id' => 20, 'name' => 'Cabarroguis'],
                ['province_id' => 20, 'name' => 'Aglipay'],
                ['province_id' => 20, 'name' => 'Diffun'],
                ['province_id' => 20, 'name' => 'Maddela'],
                ['province_id' => 20, 'name' => 'Nagtipunan'],
                ['province_id' => 20, 'name' => 'Saguday']
            ]],
            ['id' => 21, 'name' => 'Aurora', 'cities' => [
                ['province_id' => 21, 'name' => 'Baler'],
                ['province_id' => 21, 'name' => 'Casiguran'],
                ['province_id' => 21, 'name' => 'Dilasag'],
                ['province_id' => 21, 'name' => 'Dinalungan'],
                ['province_id' => 21, 'name' => 'Dingalan'],
                ['province_id' => 21, 'name' => 'Dipaculao'],
                ['province_id' => 21, 'name' => 'Maria Aurora'],
                ['province_id' => 21, 'name' => 'San Luis']
            ]],
            ['id' => 22, 'name' => 'Nueva Ecija', 'cities' => [
                ['province_id' => 22, 'name' => 'Cabanatuan City'],
                ['province_id' => 22, 'name' => 'Gapan City'],
                ['province_id' => 22, 'name' => 'Muñoz City'],
                ['province_id' => 22, 'name' => 'Palayan City'],
                ['province_id' => 22, 'name' => 'San Jose City'],
                ['province_id' => 22, 'name' => 'Aliaga'],
                ['province_id' => 22, 'name' => 'Bongabon'],
                ['province_id' => 22, 'name' => 'Cabiao'],
                ['province_id' => 22, 'name' => 'Carranglan'],
                ['province_id' => 22, 'name' => 'Cuyapo'],
                ['province_id' => 22, 'name' => 'Gabaldon'],
                ['province_id' => 22, 'name' => 'General Mamerto Natividad'],
                ['province_id' => 22, 'name' => 'General Tinio'],
                ['province_id' => 22, 'name' => 'Guimba'],
                ['province_id' => 22, 'name' => 'Jaen'],
                ['province_id' => 22, 'name' => 'Laur'],
                ['province_id' => 22, 'name' => 'Licab'],
                ['province_id' => 22, 'name' => 'Llanera'],
                ['province_id' => 22, 'name' => 'Lupao'],
                ['province_id' => 22, 'name' => 'Nampicuan'],
                ['province_id' => 22, 'name' => 'Pantabangan'],
                ['province_id' => 22, 'name' => 'Peñaranda'],
                ['province_id' => 22, 'name' => 'Quezon'],
                ['province_id' => 22, 'name' => 'Rizal'],
                ['province_id' => 22, 'name' => 'San Antonio'],
                ['province_id' => 22, 'name' => 'San Isidro'],
                ['province_id' => 22, 'name' => 'San Leonardo'],
                ['province_id' => 22, 'name' => 'Santa Rosa'],
                ['province_id' => 22, 'name' => 'Santo Domingo'],
                ['province_id' => 22, 'name' => 'Talavera'],
                ['province_id' => 22, 'name' => 'Talugtug'],
                ['province_id' => 22, 'name' => 'Zaragoza']
            ]],
            ['id' => 23, 'name' => 'Pampanga', 'cities' => [
                ['province_id' => 23, 'name' => 'Angeles City'],
                ['province_id' => 23, 'name' => 'San Fernando City'],
                ['province_id' => 23, 'name' => 'Apalit'],
                ['province_id' => 23, 'name' => 'Arayat'],
                ['province_id' => 23, 'name' => 'Bacolor'],
                ['province_id' => 23, 'name' => 'Candaba'],
                ['province_id' => 23, 'name' => 'Floridablanca'],
                ['province_id' => 23, 'name' => 'Guagua'],
                ['province_id' => 23, 'name' => 'Lubao'],
                ['province_id' => 23, 'name' => 'Mabalacat'],
                ['province_id' => 23, 'name' => 'Macabebe'],
                ['province_id' => 23, 'name' => 'Magalang'],
                ['province_id' => 23, 'name' => 'Masantol'],
                ['province_id' => 23, 'name' => 'Mexico'],
                ['province_id' => 23, 'name' => 'Minalin'],
                ['province_id' => 23, 'name' => 'Porac'],
                ['province_id' => 23, 'name' => 'San Luis'],
                ['province_id' => 23, 'name' => 'San Simon'],
                ['province_id' => 23, 'name' => 'Santa Ana'],
                ['province_id' => 23, 'name' => 'Santa Rita'],
                ['province_id' => 23, 'name' => 'Santo Tomas'],
                ['province_id' => 23, 'name' => 'Sasmuan']
            ]],
            ['id' => 24, 'name' => 'Tarlac', 'cities' => [
                ['province_id' => 24, 'name' => 'Tarlac City'],
                ['province_id' => 24, 'name' => 'Anao'],
                ['province_id' => 24, 'name' => 'Bamban'],
                ['province_id' => 24, 'name' => 'Camiling'],
                ['province_id' => 24, 'name' => 'Capas'],
                ['province_id' => 24, 'name' => 'Concepcion'],
                ['province_id' => 24, 'name' => 'Gerona'],
                ['province_id' => 24, 'name' => 'La Paz'],
                ['province_id' => 24, 'name' => 'Mayantoc'],
                ['province_id' => 24, 'name' => 'Moncada'],
                ['province_id' => 24, 'name' => 'Paniqui'],
                ['province_id' => 24, 'name' => 'Pura'],
                ['province_id' => 24, 'name' => 'Ramos'],
                ['province_id' => 24, 'name' => 'San Clemente'],
                ['province_id' => 24, 'name' => 'San Jose'],
                ['province_id' => 24, 'name' => 'San Manuel'],
                ['province_id' => 24, 'name' => 'Santa Ignacia'],
                ['province_id' => 24, 'name' => 'Victoria']
            ]],
            ['id' => 25, 'name' => 'Zambales', 'cities' => [
                ['province_id' => 25, 'name' => 'Olongapo City'],
                ['province_id' => 25, 'name' => 'Botolan'],
                ['province_id' => 25, 'name' => 'Cabangan'],
                ['province_id' => 25, 'name' => 'Candelaria'],
                ['province_id' => 25, 'name' => 'Castillejos'],
                ['province_id' => 25, 'name' => 'Iba'],
                ['province_id' => 25, 'name' => 'Masinloc'],
                ['province_id' => 25, 'name' => 'Palauig'],
                ['province_id' => 25, 'name' => 'San Antonio'],
                ['province_id' => 25, 'name' => 'San Felipe'],
                ['province_id' => 25, 'name' => 'San Marcelino'],
                ['province_id' => 25, 'name' => 'San Narciso'],
                ['province_id' => 25, 'name' => 'Santa Cruz'],
                ['province_id' => 25, 'name' => 'Subic'],
                ['province_id' => 25, 'name' => 'Cabangan']
            ]],
            ['id' => 26, 'name' => 'Metro Manila', 'cities' => [
                ['province_id' => 26, 'name' => 'Caloocan City'],
                ['province_id' => 26, 'name' => 'Las Piñas City'],
                ['province_id' => 26, 'name' => 'Makati City'],
                ['province_id' => 26, 'name' => 'Malabon City'],
                ['province_id' => 26, 'name' => 'Mandaluyong City'],
                ['province_id' => 26, 'name' => 'Manila'],
                ['province_id' => 26, 'name' => 'Marikina City'],
                ['province_id' => 26, 'name' => 'Muntinlupa City'],
                ['province_id' => 26, 'name' => 'Navotas City'],
                ['province_id' => 26, 'name' => 'Parañaque City'],
                ['province_id' => 26, 'name' => 'Pasay City'],
                ['province_id' => 26, 'name' => 'Pasig City'],
                ['province_id' => 26, 'name' => 'Quezon City'],
                ['province_id' => 26, 'name' => 'San Juan City'],
                ['province_id' => 26, 'name' => 'Taguig City'],
                ['province_id' => 26, 'name' => 'Valenzuela City'],
                ['province_id' => 26, 'name' => 'Pateros']
            ]],
            ['id' => 27, 'name' => 'Cavite', 'cities' => [
                ['province_id' => 27, 'name' => 'Bacoor City'],
                ['province_id' => 27, 'name' => 'Cavite City'],
                ['province_id' => 27, 'name' => 'Dasmariñas City'],
                ['province_id' => 27, 'name' => 'General Trias City'],
                ['province_id' => 27, 'name' => 'Imus City'],
                ['province_id' => 27, 'name' => 'Tagaytay City'],
                ['province_id' => 27, 'name' => 'Trece Martires City'],
                ['province_id' => 27, 'name' => 'Alfonso'],
                ['province_id' => 27, 'name' => 'Amadeo'],
                ['province_id' => 27, 'name' => 'Carmona'],
                ['province_id' => 27, 'name' => 'General Emilio Aguinaldo'],
                ['province_id' => 27, 'name' => 'General Mariano Alvarez'],
                ['province_id' => 27, 'name' => 'Indang'],
                ['province_id' => 27, 'name' => 'Kawit'],
                ['province_id' => 27, 'name' => 'Magallanes'],
                ['province_id' => 27, 'name' => 'Maragondon'],
                ['province_id' => 27, 'name' => 'Mendez'],
                ['province_id' => 27, 'name' => 'Naic'],
                ['province_id' => 27, 'name' => 'Noveleta'],
                ['province_id' => 27, 'name' => 'Rosario'],
                ['province_id' => 27, 'name' => 'Silang'],
                ['province_id' => 27, 'name' => 'Tanza'],
                ['province_id' => 27, 'name' => 'Ternate']
            ]],
            ['id' => 28, 'name' => 'Laguna', 'cities' => [
                ['province_id' => 28, 'name' => 'Biñan City'],
                ['province_id' => 28, 'name' => 'Cabuyao City'],
                ['province_id' => 28, 'name' => 'Calamba City'],
                ['province_id' => 28, 'name' => 'San Pablo City'],
                ['province_id' => 28, 'name' => 'Santa Rosa City'],
                ['province_id' => 28, 'name' => 'Alaminos'],
                ['province_id' => 28, 'name' => 'Bay'],
                ['province_id' => 28, 'name' => 'Calauan'],
                ['province_id' => 28, 'name' => 'Cavinti'],
                ['province_id' => 28, 'name' => 'Famy'],
                ['province_id' => 28, 'name' => 'Kalayaan'],
                ['province_id' => 28, 'name' => 'Liliw'],
                ['province_id' => 28, 'name' => 'Los Baños'],
                ['province_id' => 28, 'name' => 'Luisiana'],
                ['province_id' => 28, 'name' => 'Lumban'],
                ['province_id' => 28, 'name' => 'Mabitac'],
                ['province_id' => 28, 'name' => 'Magdalena'],
                ['province_id' => 28, 'name' => 'Majayjay'],
                ['province_id' => 28, 'name' => 'Nagcarlan'],
                ['province_id' => 28, 'name' => 'Paete'],
                ['province_id' => 28, 'name' => 'Pagsanjan'],
                ['province_id' => 28, 'name' => 'Pakil'],
                ['province_id' => 28, 'name' => 'Pangil'],
                ['province_id' => 28, 'name' => 'Pila'],
                ['province_id' => 28, 'name' => 'Rizal'],
                ['province_id' => 28, 'name' => 'Santa Cruz'],
                ['province_id' => 28, 'name' => 'Santa Maria'],
                ['province_id' => 28, 'name' => 'Siniloan'],
                ['province_id' => 28, 'name' => 'Victoria']
            ]],
            ['id' => 29, 'name' => 'Quezon', 'cities' => [
                ['province_id' => 29, 'name' => 'Lucena City'],
                ['province_id' => 29, 'name' => 'Tayabas City'],
                ['province_id' => 29, 'name' => 'Agdangan'],
                ['province_id' => 29, 'name' => 'Alabat'],
                ['province_id' => 29, 'name' => 'Atimonan'],
                ['province_id' => 29, 'name' => 'Buenavista'],
                ['province_id' => 29, 'name' => 'Burdeos'],
                ['province_id' => 29, 'name' => 'Calauag'],
                ['province_id' => 29, 'name' => 'Candelaria'],
                ['province_id' => 29, 'name' => 'Catanauan'],
                ['province_id' => 29, 'name' => 'Dolores'],
                ['province_id' => 29, 'name' => 'General Luna'],
                ['province_id' => 29, 'name' => 'General Nakar'],
                ['province_id' => 29, 'name' => 'Guinayangan'],
                ['province_id' => 29, 'name' => 'Gumaca'],
                ['province_id' => 29, 'name' => 'Infanta'],
                ['province_id' => 29, 'name' => 'Jomalig'],
                ['province_id' => 29, 'name' => 'Lopez'],
                ['province_id' => 29, 'name' => 'Macalelon'],
                ['province_id' => 29, 'name' => 'Mauban'],
                ['province_id' => 29, 'name' => 'Mulanay'],
                ['province_id' => 29, 'name' => 'Padre Burgos'],
                ['province_id' => 29, 'name' => 'Pagbilao'],
                ['province_id' => 29, 'name' => 'Panukulan'],
                ['province_id' => 29, 'name' => 'Patnanungan'],
                ['province_id' => 29, 'name' => 'Perez'],
                ['province_id' => 29, 'name' => 'Pitogo'],
                ['province_id' => 29, 'name' => 'Plaridel'],
                ['province_id' => 29, 'name' => 'Polillo'],
                ['province_id' => 29, 'name' => 'Quezon'],
                ['province_id' => 29, 'name' => 'Real'],
                ['province_id' => 29, 'name' => 'Sampaloc'],
                ['province_id' => 29, 'name' => 'San Andres'],
                ['province_id' => 29, 'name' => 'San Antonio'],
                ['province_id' => 29, 'name' => 'San Francisco'],
                ['province_id' => 29, 'name' => 'San Narciso'],
                ['province_id' => 29, 'name' => 'Sariaya'],
                ['province_id' => 29, 'name' => 'Tagkawayan'],
                ['province_id' => 29, 'name' => 'Tiaong'],
                ['province_id' => 29, 'name' => 'Unisan']
            ]],
            ['id' => 30, 'name' => 'Rizal', 'cities' => [
                ['province_id' => 30, 'name' => 'Antipolo City'],
                ['province_id' => 30, 'name' => 'Angono'],
                ['province_id' => 30, 'name' => 'Baras'],
                ['province_id' => 30, 'name' => 'Binangonan'],
                ['province_id' => 30, 'name' => 'Cainta'],
                ['province_id' => 30, 'name' => 'Cardona'],
                ['province_id' => 30, 'name' => 'Jalajala'],
                ['province_id' => 30, 'name' => 'Morong'],
                ['province_id' => 30, 'name' => 'Pililla'],
                ['province_id' => 30, 'name' => 'Rodriguez'],
                ['province_id' => 30, 'name' => 'San Mateo'],
                ['province_id' => 30, 'name' => 'Tanay'],
                ['province_id' => 30, 'name' => 'Taytay'],
                ['province_id' => 30, 'name' => 'Teresa']
            ]],
            ['id' => 31, 'name' => 'Marinduque', 'cities' => [
                ['province_id' => 31, 'name' => 'Boac'],
                ['province_id' => 31, 'name' => 'Buenavista'],
                ['province_id' => 31, 'name' => 'Gasan'],
                ['province_id' => 31, 'name' => 'Mogpog'],
                ['province_id' => 31, 'name' => 'Santa Cruz'],
                ['province_id' => 31, 'name' => 'Torrijos']
            ]],
            ['id' => 32, 'name' => 'Occidental Mindoro', 'cities' => [
                ['province_id' => 32, 'name' => 'Abra de Ilog'],
                ['province_id' => 32, 'name' => 'Calintaan'],
                ['province_id' => 32, 'name' => 'Looc'],
                ['province_id' => 32, 'name' => 'Lubang'],
                ['province_id' => 32, 'name' => 'Magsaysay'],
                ['province_id' => 32, 'name' => 'Mamburao'],
                ['province_id' => 32, 'name' => 'Paluan'],
                ['province_id' => 32, 'name' => 'Rizal'],
                ['province_id' => 32, 'name' => 'Sablayan'],
                ['province_id' => 32, 'name' => 'San Jose'],
                ['province_id' => 32, 'name' => 'Santa Cruz']
            ]],
            ['id' => 33, 'name' => 'Oriental Mindoro', 'cities' => [
                ['province_id' => 33, 'name' => 'Calapan City'],
                ['province_id' => 33, 'name' => 'Baco'],
                ['province_id' => 33, 'name' => 'Bansud'],
                ['province_id' => 33, 'name' => 'Bongabong'],
                ['province_id' => 33, 'name' => 'Bulalacao'],
                ['province_id' => 33, 'name' => 'Gloria'],
                ['province_id' => 33, 'name' => 'Mansalay'],
                ['province_id' => 33, 'name' => 'Naujan'],
                ['province_id' => 33, 'name' => 'Pinamalayan'],
                ['province_id' => 33, 'name' => 'Pola'],
                ['province_id' => 33, 'name' => 'Puerto Galera'],
                ['province_id' => 33, 'name' => 'Roxas'],
                ['province_id' => 33, 'name' => 'San Teodoro'],
                ['province_id' => 33, 'name' => 'Socorro'],
                ['province_id' => 33, 'name' => 'Victoria']
            ]],
            ['id' => 34, 'name' => 'Palawan', 'cities' => [
                ['province_id' => 34, 'name' => 'Puerto Princesa City'],
                ['province_id' => 34, 'name' => 'Aborlan'],
                ['province_id' => 34, 'name' => 'Agutaya'],
                ['province_id' => 34, 'name' => 'Araceli'],
                ['province_id' => 34, 'name' => 'Balabac'],
                ['province_id' => 34, 'name' => 'Bataraza'],
                ['province_id' => 34, 'name' => 'Brooke’s Point'],
                ['province_id' => 34, 'name' => 'Busuanga'],
                ['province_id' => 34, 'name' => 'Cagayancillo'],
                ['province_id' => 34, 'name' => 'Coron'],
                ['province_id' => 34, 'name' => 'Culion'],
                ['province_id' => 34, 'name' => 'Cuyo'],
                ['province_id' => 34, 'name' => 'Dumaran'],
                ['province_id' => 34, 'name' => 'El Nido'],
                ['province_id' => 34, 'name' => 'Kalayaan'],
                ['province_id' => 34, 'name' => 'Linapacan'],
                ['province_id' => 34, 'name' => 'Magsaysay'],
                ['province_id' => 34, 'name' => 'Narra'],
                ['province_id' => 34, 'name' => 'Quezon'],
                ['province_id' => 34, 'name' => 'Rizal'],
                ['province_id' => 34, 'name' => 'Roxas'],
                ['province_id' => 34, 'name' => 'San Vicente'],
                ['province_id' => 34, 'name' => 'Sofronio Española'],
                ['province_id' => 34, 'name' => 'Taytay']
            ]],
            ['id' => 35, 'name' => 'Romblon', 'cities' => [
                ['province_id' => 35, 'name' => 'Alcantara'],
                ['province_id' => 35, 'name' => 'Banton'],
                ['province_id' => 35, 'name' => 'Cajidiocan'],
                ['province_id' => 35, 'name' => 'Calatrava'],
                ['province_id' => 35, 'name' => 'Concepcion'],
                ['province_id' => 35, 'name' => 'Corcuera'],
                ['province_id' => 35, 'name' => 'Ferrol'],
                ['province_id' => 35, 'name' => 'Looc'],
                ['province_id' => 35, 'name' => 'Magdiwang'],
                ['province_id' => 35, 'name' => 'Odiongan'],
                ['province_id' => 35, 'name' => 'Romblon'],
                ['province_id' => 35, 'name' => 'San Agustin'],
                ['province_id' => 35, 'name' => 'San Andres'],
                ['province_id' => 35, 'name' => 'San Fernando'],
                ['province_id' => 35, 'name' => 'San Jose'],
                ['province_id' => 35, 'name' => 'Santa Fe'],
                ['province_id' => 35, 'name' => 'Santa Maria']
            ]],
        ];

        foreach($province as $prov) {
            $pro = Routes::create([
                'name' => $prov['name']
            ]);

            foreach($prov['cities'] as $city) {
                RouteCities::create([
                    'route_id' => $pro->id,
                    'name' => $city['name']
                ]);
            }
        }

    }
}
